In [1]:
import numpy as np
import sys

In [2]:
a = np.array([1,2.5,3.6,4.2])

In [3]:
a[:]

array([1. , 2.5, 3.6, 4.2])

In [4]:
a = a.astype("int32")

In [5]:
a

array([1, 2, 3, 4], dtype=int32)

In [6]:
b = np.array(['we','qw','er'])

In [7]:
b.dtype

dtype('<U2')

In [8]:
d = np.array([{'a': 1}, sys])

In [9]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [10]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0,0,0]]])


In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 0, 0]]])

In [12]:
c.ndim

3

In [78]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [21]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
a @ b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [25]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
l = list(range(1000))
a = np.arange(1000)

In [27]:
%time np.sum(a**2)

CPU times: user 640 µs, sys: 808 µs, total: 1.45 ms
Wall time: 1.17 ms


332833500

In [28]:
%time sum([x ** 2 for x in l])

CPU times: user 533 µs, sys: 205 µs, total: 738 µs
Wall time: 745 µs


332833500

In [29]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays :",
	(time.time() - initialTime),
	"seconds")


Time taken by Lists : 0.07529091835021973 seconds
Time taken by NumPy Arrays : 0.0031239986419677734 seconds


# Some numpy functions

In [30]:
np.random

<module 'numpy.random' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/random/__init__.py'>

In [31]:
data = [1, 2, 3, 4, 5]
random_sample = np.random.choice(data, size=3, replace=False)

In [32]:
random_sample

array([3, 2, 4])

In [33]:
random_uniform = np.random.uniform(low=0, high=1, size=10)

In [34]:
random_uniform

array([0.41784014, 0.26597717, 0.49504622, 0.82415148, 0.63793726,
       0.92903321, 0.21776276, 0.17204667, 0.29786536, 0.4375435 ])

In [35]:
np.random.normal(size=2)

array([-2.22090016,  2.0401398 ])

In [36]:
random_normal = np.random.normal(loc=0, scale=1, size=10)
random_normal

array([-1.42834938,  0.11549893, -0.62305235,  1.54263443,  0.59790933,
        1.06928576, -1.46894017, -0.63793334,  0.44452963, -0.38891608])

In [37]:
random_matrix = np.random.random((3, 3))  # Generates a 3x3 matrix of random values
random_matrix

array([[0.54776779, 0.91185205, 0.23990944],
       [0.22112726, 0.70297637, 0.82314359],
       [0.82816663, 0.09022612, 0.58705439]])

In [48]:
np.random.rand(2, 4)

array([[0.69690023, 0.16549259, 0.11508857, 0.11857432],
       [0.3322908 , 0.47224746, 0.36481771, 0.02353038]])

In [53]:
import numpy as np

a = 5  # Lower bound of the interval
b = 10  # Upper bound of the interval
shape = (2, 4)  # Shape of the output array

random_numbers = a + (b - a) * np.random.rand(*shape)
print(random_numbers)

[[5.0146659  8.54735365 8.20465445 8.75921253]
 [8.96533327 8.33245656 8.50294952 5.27967279]]


In [54]:
5.0146659 - 5

0.014665899999999787

In [55]:
0.014665899999999787/5

0.0029331799999999576

In [58]:
import numpy as np

low = 0    # Lower bound of the range (inclusive)
high = 10  # Upper bound of the range (exclusive)
size = (3, 3)  # Shape of the matrix

random_matrix = np.random.randint(low, high, size)
print(random_matrix)

[[8 9 3]
 [7 7 7]
 [1 1 8]]


In [59]:
np.arange(4)

array([0, 1, 2, 3])

In [62]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [69]:
np.arange(10).reshape (2, 5) #must be even number so that it can be easily split

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
np.linspace(0, 10, 6).astype("int8")

array([ 0,  2,  4,  6,  8, 10], dtype=int8)

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
a.shape

(3, 3)

In [93]:
a.size

9

In [94]:
a.ndim

2

In [102]:
numpy.linspace(a, a.size +1, 5, endpoint=True, retstep=True, dtype=None, axis=1)

(array([[[ 1.  ,  2.  ,  3.  ],
         [ 3.25,  4.  ,  4.75],
         [ 5.5 ,  6.  ,  6.5 ],
         [ 7.75,  8.  ,  8.25],
         [10.  , 10.  , 10.  ]],
 
        [[ 4.  ,  5.  ,  6.  ],
         [ 5.5 ,  6.25,  7.  ],
         [ 7.  ,  7.5 ,  8.  ],
         [ 8.5 ,  8.75,  9.  ],
         [10.  , 10.  , 10.  ]],
 
        [[ 7.  ,  8.  ,  9.  ],
         [ 7.75,  8.5 ,  9.25],
         [ 8.5 ,  9.  ,  9.5 ],
         [ 9.25,  9.5 ,  9.75],
         [10.  , 10.  , 10.  ]]]),
 array([[2.25, 2.  , 1.75],
        [1.5 , 1.25, 1.  ],
        [0.75, 0.5 , 0.25]]))

In [106]:
np.linspace(0, 1, 9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [116]:
a = np.zeros((2,5), dtype="int")
a.dtype

dtype('int64')

In [117]:
np.ones(4, dtype="int8")

array([1, 1, 1, 1], dtype=int8)

In [127]:
np.empty((2,4), dtype='int8')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [128]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [134]:
numpy.eye(N=4, M=3, k=-1, dtype=int, order='C')

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [135]:
numpy.eye(N=4, M=3, k=0, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [136]:
numpy.eye(N=4, M=3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [138]:
numpy.eye(N=4, M=None, k=0, dtype=int, order='C')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [140]:
'Hello World'[6]

'W'