In [2]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

In [8]:
b = np.array([[1,2,3],[1.3,1.0,2.0]])

b

array([[1. , 2. , 3. ],
       [1.3, 1. , 2. ]])

In [12]:
# Finding The Dimension Of Your Numpy Array
print(a.ndim)
print(b.ndim)

1
2


In [14]:
# Finding the shape of the numpy array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [19]:
# Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [22]:
# As we can see, the array a is of type int64 by default so it takes more memory. But we want it to take less memory. So we can specify the dtype when initialising the numpy array as shown below
c = np.array([1,2,3], dtype='int32')
d = np.array([1,2,3], dtype='int16') #even lower

In [24]:
print(c.dtype)
print(d.dtype)
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print(d.itemsize)

int32
int16
8
8
4
2


In [23]:
#indexing numpy arrays
a = np.array([ [1,2,3,4,5,6,7], [8,9,10,11,12,13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [26]:
a[1,3]

11

In [14]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [27]:
a[1,:] # specific row

array([ 8,  9, 10, 11, 12, 13, 14])

In [28]:
a[:,3] # specific column

array([ 4, 11])

In [8]:
# alternating indexes
a[1, 1::2]

array([ 9, 11, 13])

In [45]:
#making changes to an element
a[0,5] = 69
a

array([[ 1,  2,  3,  4,  5, 69,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [46]:
a[1,:] = 5
a

array([[ 1,  2,  3,  4,  5, 69,  7],
       [ 5,  5,  5,  5,  5,  5,  5]])

In [47]:
a[:,3]=[1,2]
a

array([[ 1,  2,  3,  1,  5, 69,  7],
       [ 5,  5,  5,  2,  5,  5,  5]])

In [10]:
# 3D EXAMPLE
b = np.array([[ [1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# indexing in a 3D array
# print(b[1,1,1])
print(b[:,1,:])

[[3 4]
 [7 8]]


In [56]:
b[:,1,:] = [[1,2],[3,4]]
b

array([[[1, 2],
        [1, 2]],

       [[5, 6],
        [3, 4]]])

In [18]:
#all zero matrix
np.zeros((2,2,2), dtype='int16') #by default it is of type float but it can be changed to a specific dtype, just like any other numpy array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int16)

In [19]:
# All 1s matrix
a = np.ones((2,2,2))
a.dtype

dtype('float64')

In [20]:
# Creating a numpy array with all of one specified element
np.full((2,3),69)

array([[69, 69, 69],
       [69, 69, 69]])

In [69]:
# Creating an array that has the same shape as a specified array
# np.full_like(a,69)
np.full(a.shape,69)

array([[69, 69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69, 69]])

In [77]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.35911827, 0.69787194, 0.15405103],
        [0.71068226, 0.38259741, 0.50728042]],

       [[0.58634911, 0.56563694, 0.10476708],
        [0.83917436, 0.22323207, 0.23308851]],

       [[0.40488961, 0.88874087, 0.60518574],
        [0.28883831, 0.15688682, 0.51768331]],

       [[0.90676534, 0.28715962, 0.51256853],
        [0.10838857, 0.54998305, 0.45211939]]])

In [24]:
# Creating a random numpy array with the shape of an existing array
np.random.random_sample(a.shape)

array([[0.97171215, 0.15105126, 0.27246117, 0.77561589, 0.44797161,
        0.4251149 , 0.14964514],
       [0.77533386, 0.26784049, 0.37135538, 0.24898762, 0.09668924,
        0.69345705, 0.37907405]])

In [31]:
np.random.randint(0,9, size=(2,2))

array([[8, 7],
       [9, 5]])

In [26]:
# Creating an identity matrix 
i = np.identity(3,dtype='int16')
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [91]:
# Repeating rows of an array
a = np.array([[1,2,3]])
a2 = np.repeat(a, 3, axis=0)
a2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [34]:
a = np.ones((5,5))

In [35]:
a[1:4,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
a[2,2]=9
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# WHEN WE INITIALISE AN ARRAY WITH ANOTHER ONE AND THEN UPDATE THE NEW ONE THEN THE OLD ONE ALSO GETS UPDATED
a = np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
b = a
b

array([1, 2, 3])

In [39]:
b[0] = 100
b

array([100,   2,   3])

In [40]:
a

array([100,   2,   3])

In [43]:
a+b

array([2, 4, 6])

In [123]:
a+2

array([3, 4, 5])

In [124]:
a-2

array([-1,  0,  1])

Elementwise mathematical operations

In [44]:
b = np.array([0,30,45,60,90], dtype='int32')
b_deg = np.deg2rad(b)
b_deg = np.sin(b_deg)

In [45]:
b_deg

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

#### Diagonal indexing

In [64]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
x=0 
y=0
z = a.shape[1]
# print(z)
while z > y:
    print(a[y,x])
    x+=1
    y+=1
    # z-=1

1
6
11
16


In [65]:
a[[0,2],2:4]

array([[ 3,  4],
       [11, 12]])

In [71]:
a = np.array([[1,2]])
b = np.array([3,4])
c = np.hstack((a,b))
c

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)